plugins {
    id 'fabric-loom' version '1.5.8'
    id 'java'
}

repositories {
    maven {
        name = '阿里云'
        url = 'https://maven.aliyun.com/repository/public'
    }
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
    mavenCentral()
    gradlePluginPortal()
}

group = project.maven_group
archivesBaseName = project.archives_base_name
version = project.mod_version

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    
    configurations.all {
        exclude group: 'io.netty', module: 'netty-transport-native-epoll'
    }
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}